In [1]:
import requests
import pandas as pd

In [2]:
url = "https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1
}

response = requests.get(url, params=params)

data = response.json()

In [3]:
df = pd.DataFrame(data)

df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,67308.000000,1346169836035,1,1346171114936,25873277720,68174.00,...,1.999941e+07,2.100000e+07,126080.00,-46.61493,2025-10-06T18:57:42.558Z,67.810000,9.916092e+04,2013-07-06T00:00:00.000Z,None,2026-03-08T07:48:13.786Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1953.900000,235829932720,2,235829932720,10652281952,1991.26,...,1.206921e+08,NaN,4946.05,-60.49569,2025-08-24T19:21:03.333Z,0.432979,4.511697e+05,2015-10-20T00:00:00.000Z,"{'times': 37.8140626890622, 'currency': 'btc',...",2026-03-08T07:48:13.841Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999883,183950728945,3,189417082183,41316314789,1.00,...,1.894373e+11,NaN,1.32,-24.42673,2018-07-24T00:00:00.000Z,0.572521,7.464973e+01,2015-03-02T00:00:00.000Z,None,2026-03-08T07:48:12.346Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,619.920000,84540082558,4,84540081424,541436083,629.89,...,1.363584e+08,2.000000e+08,1369.99,-54.74978,2025-10-13T08:41:24.131Z,0.039818,1.556806e+06,2017-10-19T00:00:00.000Z,None,2026-03-08T07:48:13.608Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.360000,83310353629,5,136046693768,1323522324,1.37,...,9.998570e+10,1.000000e+11,3.65,-62.68475,2025-07-18T03:40:53.808Z,0.002686,5.055341e+04,2014-05-22T00:00:00.000Z,None,2026-03-08T07:48:12.051Z

In [4]:
df = df[[
    "name",
    "symbol",
    "current_price",
    "market_cap",
    "total_volume"
]]

df.head()

       name symbol  current_price     market_cap  total_volume
0   Bitcoin    btc   67308.000000  1346169836035   25873277720
1  Ethereum    eth    1953.900000   235829932720   10652281952
2    Tether   usdt       0.999883   183950728945   41316314789
3       BNB    bnb     619.920000    84540082558     541436083
4       XRP    xrp       1.360000    83310353629    1323522324

In [5]:
from datetime import datetime

df["timestamp"] = datetime.now()

df.head()

,name,symbol,current_price,market_cap,total_volume,timestamp
0,Bitcoin,btc,67308.000000,1346169836035,25873277720,2026-03-08 13:20:18.953964
1,Ethereum,eth,1953.900000,235829932720,10652281952,2026-03-08 13:20:18.953964
2,Tether,usdt,0.999883,183950728945,41316314789,2026-03-08 13:20:18.953964
3,BNB,bnb,619.920000,84540082558,541436083,2026-03-08 13:20:18.953964
4,XRP,xrp,1.360000,83310353629,1323522324,2026-03-08 13:20:18.953964

In [6]:
df.shape

(10, 6)

In [9]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Ifdxrmf4j9#123",
    database="crypto_project"
)

cursor = conn.cursor()

print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [10]:
df.head()

,name,symbol,current_price,market_cap,total_volume,timestamp
0,Bitcoin,btc,67308.000000,1346169836035,25873277720,2026-03-08 13:20:18.953964
1,Ethereum,eth,1953.900000,235829932720,10652281952,2026-03-08 13:20:18.953964
2,Tether,usdt,0.999883,183950728945,41316314789,2026-03-08 13:20:18.953964
3,BNB,bnb,619.920000,84540082558,541436083,2026-03-08 13:20:18.953964
4,XRP,xrp,1.360000,83310353629,1323522324,2026-03-08 13:20:18.953964

In [11]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Ifdxrmf4j9#123",
    database="crypto_project"
)

cursor = conn.cursor()

print("Connected to MySQL!")

Connected to MySQL!

In [13]:
for index, row in df.iterrows():

    query = """
    INSERT INTO crypto_prices
    (coin_name, symbol, price, market_cap, volume, timestamp)
    VALUES (%s, %s, %s, %s, %s, %s)
    """

    values = (
        row["name"],
        row["symbol"],
        row["current_price"],
        row["market_cap"],
        row["total_volume"],
        row["timestamp"]
    )

    cursor.execute(query, values)

conn.commit()

print("Data inserted successfully!")

Data inserted successfully!